### ISSUE TITLE
symfony 5

### ISSUE THREAD

**Issue by rulatir** [loco/loco-php-sdk#11]
Could we bump symfony dependencies to 5.0 like we bumped them to 4.0 a while ago? Lumen 7.x needs symfony 5.

**Comment by timwhitlock** [comment]
Feel free to submit a pull request for this. I am not a Symfony developer and don't have the time right now to test under Symfony 5.

**Comment by rulatir** [comment]
Is the functionality that uses symfony tested? I understand (hopefully correctly) that it is only used by scripts under bin/?

Are there any steps necessary beyond getting the tests all green? I see that the repo contains committed generated code. If I don't change the input/specs, is it safe to assume that the generated code won't be affected by a mere dependency version bump?

**Comment by timwhitlock** [comment]
It's just the console, which yes, is only used under bin. But that doesn't mean I want to break it. People could still be using it in their deployments.

You don't need to build any generated code unless the API changes, which it hasn't.

I'm unsure what's safe to assume, which is why I said I didn't have time to look into it. I think if the tests pass and the console works then it's good to go. I will probably leave the changes on master until the next API change though.

**Comment by rulatir** [comment]
Any chance you might tag 2.0.8?
