### ISSUE TITLE
dont depend on guzzle/guzzle

### ISSUE THREAD

**Issue by gemal** [loco/loco-php-sdk#2]
guzzle/guzzle is deprecated and guzzlehttp/guzzle should be used instead

https://packagist.org/packages/guzzle/guzzle

**Comment by timwhitlock** [comment]
I'm aware of this and even spoke to the author about it. The last time I checked, updating this dependency would require a complete rewrite of my package. Particularly because the [service builder](https://github.com/loco/swizzle) would no longer work.

**Comment by Nyholm** [comment]
I think I can help to remove the Guzzle dependency and introduce HTTPlug. Are you interested?

**Comment by timwhitlock** [comment]
I'm interested in any drop-in replacement, if you think it's necessary. Thanks.

**Comment by Nyholm** [comment]
Hm, looking closer to the code. The current API client is depending on Guzzle/Services. 
The easiest would be to update to Guzzle/Services 1.0 (they just tagged a stable release =)), but that will still make us Guzzle dependent. 

What I *had* in mind what to use HTTPlug, that would allow users to choose what HTTP client they want. Ie there is no Guzzle5/6 issue. Using HTTPlug and not Guzzle/Services would be a big rewrite. 

What is the status of the API? As far as I can tell it is pretty stable. Are there any refactorization on the public endpoints planned?

**Comment by timwhitlock** [comment]
No specific changes are planned, but new platform features will result in endpoints being added. I tend to avoid breaking changes to existing endpoints, but from time to time the platform itself will have features removed.

The current service descriptions allow me to update the client and the documentation automatically whenever the API changes. Reimplementing that workflow is not something I intend to do unless it becomes essential.

I would love to see the community producing better client libraries than my one, and I'll happily link to third party projects from my [docs](https://localise.biz/api/). My suggestion is to start from scratch rather than build upon this project. Let me know if you produce something that works for you and I'll link to it.

**Comment by Nyholm** [comment]
I agree. that will probably be the best solution. 

As always, thank you for a quick response.

**Comment by johndodev** [comment]
Since we couldn't either use this sdk, I just started a new one for our usages here, very simple, and I think more compliant to sdk usage (more "classic" in the way to use it).

There is no models yet, but I'm not sure adding some is a good idea, as without it, the sdk will "upgrade" automatically with the api.

There are very few methods, juste what we need here for now, but adding some should also be very easy. 

Also phpunit tests should arrive one day.

If you think something is wrong, tell me ?

https://github.com/johndodev/loco-php-sdk

**Comment by timwhitlock** [comment]
Thanks @johndodev this is great to see.
I'm watching your project and will link to it once it's more complete. If I have any comments, I'll add them in your repository issues, rather than here.

Just one thing, your wording implies it is "The" SDK for Loco. I'd appreciate it if you indicated it is unofficial, or at least one alternative.

Thanks!

**Comment by Nyholm** [comment]
@johndodev I've also started a client. There is just a few endpoints implemented (the once I need) but they are completed with domain models. 

See https://github.com/FriendsOfApi/localise.biz

We follow the bootstrap from: https://github.com/FriendsOfApi/boilerplate

**Comment by johndodev** [comment]
@timwhitlock Done.

**Comment by timwhitlock** [comment]
The master branch now depends on Guzzle 6 and will be released as v2.0 shortly.
